language: ruby

sudo: required

services:
  - docker

install:
  - docker run -v `pwd`:/caddy-docker -w /caddy-docker golang:latest bash -c "cd /caddy-docker; ./build_caddy.sh"

jobs:
  include:
    - stage: test
      if: (NOT type IN (pull_request)) AND (branch = master)
      script:
        - tag=$TRAVIS_BRANCH-`git rev-parse --short HEAD`
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker build -t vedhavyas/caddy:latest .
        - docker tag vedhavyas/caddy:latest vedhavyas/caddy:$tag
        - docker push vedhavyas/caddy:$tag
        - docker push vedhavyas/caddy:latest
